### ISSUE TITLE
get_obb_from_labelim() doesn't handle touching and rotated labels well

### ISSUE THREAD

**Issue by GenevieveBuckley** [VolkerH/np_obb#7]
It seems that `np_obb.get_obb_from_labelim()` doesn't correctly identify oriented bounding boxes when the labels are touching and rotated from the image axis. Is this expected behaviour?

```python
labels = skimage.io.imread("img_rotated.png")
obbs = np_obb.get_obb_from_labelim(labels)

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111)
ax.imshow(labels)
for i in obbs.keys():
    corners, centre = obbs[i]
    ax.scatter(centre[1],centre[0])    
    ax.plot(corners[:,1],corners[:,0],'-')
plt.show()
```
![image](https://user-images.githubusercontent.com/30920819/59824301-13d92c80-9374-11e9-968e-cb18bab78fe7.png)

But it does seem to work as expected if the same image is not rotated:

![image](https://user-images.githubusercontent.com/30920819/59824318-205d8500-9374-11e9-99dd-fccb863fe35b.png)

I have a project where I need to split one object up into multiple parts, and I thought this method would be more elegant that what I've got now.

**Comment by GenevieveBuckley** [comment]
For completeness, here are the two simulated image files I used:

`img_rotated.png`
![img_rotated](https://user-images.githubusercontent.com/30920819/59824493-a11c8100-9374-11e9-940d-02f79830ea9e.png)

`img.png`
![img](https://user-images.githubusercontent.com/30920819/59824501-a5e13500-9374-11e9-9b80-21d6b72eeeae.png)

**Comment by VolkerH** [comment]
Hi Genevieve,

that is weird behaviour indeed. It seems as if the bounding boxes are getting progressively bigger.
I would call that a bug. 

I'm not sure when I get to look into that. I'll have a look at it during my commute on Monday. 

You mention touching labels, does it go away if there is a gap between labels? Would it be easy for you to create this test image with every second label slice equal to the background?

**Comment by GenevieveBuckley** [comment]
Oooh, you know what I think has happened? I think the rotation has caused some of the grayscale values at the border of the shape to become altered - so it's not a true label image anymore. I'll try it again with the anti-aliasing off.

**Comment by VolkerH** [comment]
Just was typing this:

The problem appears to be your sample image. Not sure whether that happens during rotation ?

![image](https://user-images.githubusercontent.com/2210044/59827526-3ff8ab80-937c-11e9-945a-b3942016e349.png)

closing.
Feel free to reopen if I'm wrong.

**Comment by GenevieveBuckley** [comment]
Typing at the same time :)
Have a good night!
