### ISSUE TITLE
does not give the correct OBB for a specific case

### ISSUE THREAD

**Issue by twut** [VolkerH/np_obb#9]
Hi VolkerH,

First, thanks for this useful python library.
I used this library for creating OBB for my datasets. For only one dataset (dimension (N,2) 2D points), the function did not return the smallest OBB.
![image](https://user-images.githubusercontent.com/47453077/79073929-a5da6900-7ce9-11ea-9f67-b959906ae8f8.png)

The points are attached with dimension (133,2)
[32 tweeendertigste verdiepingPoint_Cluster1.txt](https://github.com/VolkerH/np_obb/files/4466642/32.tweeendertigste.verdiepingPoint_Cluster1.txt)

**Comment by VolkerH** [comment]
Hi @twut,
thanks for the feedback and the bug report. Give me a few days to look into it.

**Comment by VolkerH** [comment]
Hi @twut,

I could reproduce your example. 
I didn't dive deeply into it, but I think what was happening was related to the fact that the covariance matrix was calculated on the whole point set and the particular data set had a varying point density. (Again, just a guess). I now calculate the convex hull of the point set first and then proceed to determine the OBB. 

That fixes your example: (blue is old BB, red is BB after convex hull)
![image](https://user-images.githubusercontent.com/2210044/79292783-511b3600-7f15-11ea-9cd0-a16eeee4fd3f.png)

Note that the current algorithm does not give a guarantee that the OBB is optimal. I am planning to rewrite this whole function using rotating calipers and provide the option to find the minimum area and minimum perimeter OBBs.

Thanks for pointing out this particular example.

**Comment by twut** [comment]
Thanks a lot! 
I think you are right. The reason for this issue is the density of the input dataset. 
I tried to change the density of the input data everywhere the same. When the density of each edge is the same, it gives me the correct smallest OBB. When the density of one edge is higher than others, the OBB rotates.

**Comment by VolkerH** [comment]
I also worked on the rotating calipers implementation today. Nearly finished. It will always give the optimal result, so check back in a week or so.

**Comment by VolkerH** [comment]
Just mentioning this here in case it is of interest: 
OpenCV has an implementation that will give the minimum area rectangle
https://docs.opencv.org/3.4/de/d62/tutorial_bounding_rotated_ellipses.html
